### ISSUE TITLE
Library?

### ISSUE THREAD

**Issue by fungos** [mgerhardy/fips-polyvox#1]
Is this working? I do not see any CMakeLists.txt to build the project library. How are you using it?

**Comment by mgerhardy** [comment]
Yes, this works - it's a header only lib. You just need to add the lib to your fips.yml and everything's fine

**Comment by fungos** [comment]
Ok, this means the code in library/PolyVoxCore/ is not used?

**Comment by mgerhardy** [comment]
It looks like you are not referring to the correct hash - there is a development branch where they converted the lib to a header only lib.

**Comment by mgerhardy** [comment]
And I didn't add a cmake file for the examples  because they are basing on qt...

**Comment by fungos** [comment]
Weird. I was looking from bitbucket directly in the browser. Anyway, I will try to use it. Thanks!

**Comment by mgerhardy** [comment]
It is the develop branch. Btw. If you use it and get ambient occlusion
working, please let me know ;)

**Comment by fungos** [comment]
Maybe you will be interested in this:
https://github.com/nothings/stb/blob/master/stb_voxel_render.h

**Comment by mgerhardy** [comment]
Thanks a lot for the link - looks very interesting
